#ifndef PEARSIGNALS_H
#define PEARSIGNALS_H


//      OVERDEFINING SIGNAL
#define     pearSignal     int8_t

//      OVERDEFINING INDEXER
#define     indexer     	size_t

//      SIGNALS TO LISTWIDGET
enum SignalsListWidget
{
    DEFAULT_LISTWIDGET_OUTPUT           = 0x00000000,
    ONLYFOLDERS_LISTWIDGET_OUTPUT   	= 0x00000001,
    ONLYFILES_LISTWIDGET_OUTPUT     	= 0x00000002
};


//		SIGNALS TO RENAME PATTERN
enum SignalsRenamePattern
{
    USE_NUMBERS_IN_PATTERN	= 0x00000000,
    USE_LETTERS_IN_PATTERN	= 0x00000001
};


#endif // PEARSIGNALS_H
